### ISSUE TITLE
Require luxon as a dependency

### ISSUE THREAD

**Issue by jpike88** [Agranom/ngx-material-timepicker#147]
I'd rather not have to remember that luxon has to be installed if this library has it has a hard requirement. It should be pulled in as a dependency automatically.

**Comment by Emxm3** [comment]
^ Aaaaand this comment just solved my issue.....

**Comment by jpike88** [comment]
@Agranom poke...

**Comment by Agranom** [comment]
I'll check the possibility.

**Comment by Agranom** [comment]
Done

**Comment by tolotrasamuel** [comment]
It also require @types/luxon to be installed otherwise, angular compiler fails

**Comment by Agranom** [comment]
I'll check it

**Comment by mackelito** [comment]
Looks like this issue has made a comeback? :D

**Comment by jpike88** [comment]
It still shows as a dependency in package.json, what exactly is the problem

**Comment by mackelito** [comment]
My bad! 😬
the package.json was not up to snuff! 😁
